---
name: Build atomic
on: # yamllint disable-line rule:truthy rule:comments
  schedule:
    # yamllint disable-line rule:comments
    - cron: "41 6 * * 0" # 6:41 UTC Sunday
    # yamllint disable-line rule:comments
    - cron: "41 6 * * 1,2,3,4,5,6" # 6:41 UTC Monday-Saturday
  # pull_request:
  #   branches:
  #     - main
  merge_group:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Flavor"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - beta
          - both
      build_type:
        description: "Build Type"
        required: true
        default: "image"
        type: choice
        options:
          - image
          - iso
          - both

jobs:
  lint:
    name: Lint Project
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  build-image:
    name: Build Images
    needs: [lint]
    if: |
      (github.event_name == 'schedule') ||
      (github.event_name == 'merge_group') ||
      (github.event_name == 'workflow_dispatch' &&
        (inputs.flavor == 'stable' || inputs.flavor == 'both') &&
        (inputs.build_type == 'image' || inputs.build_type == 'both'))
    uses: ./.github/workflows/build-image.yml
    permissions:
      actions: read
      contents: read
      packages: write
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    with:
      image_flavor: Stable

  build-iso:
    name: Build ISOs
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'stable' || inputs.flavor == 'both') &&
      (inputs.build_type == 'iso' || inputs.build_type == 'both') &&
      !contains(github.head_ref, 'renovate')
    uses: ./.github/workflows/build-iso.yml
    permissions:
      actions: read
      contents: read
      packages: read
    needs: [build-image]
    with:
      image_flavor: Stable

  gen-sbom:
    name: Generate SBOMs
    if: |
      !contains(github.head_ref, 'renovate') &&
      (
        (github.event_name == 'schedule') ||
        (github.event_name == 'merge_group') ||
        (github.event_name == 'workflow_dispatch' &&
          (inputs.flavor == 'stable' || inputs.flavor == 'both') &&
          (inputs.build_type == 'image' || inputs.build_type == 'both'))
      )
    needs: [build-image]
    uses: ./.github/workflows/gen-sbom.yml
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    with:
      image_flavor: Stable

  build-image-beta:
    name: Build Images (Beta)
    needs: [lint]
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'beta' || inputs.flavor == 'both') &&
      (inputs.build_type == 'image' || inputs.build_type == 'both')
    uses: ./.github/workflows/build-image.yml
    permissions:
      actions: read
      contents: read
      packages: write
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    with:
      image_flavor: Beta

  build-iso-beta:
    name: Build ISOs (Beta)
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'beta' || inputs.flavor == 'both') &&
      (inputs.build_type == 'iso' || inputs.build_type == 'both') &&
      !contains(github.head_ref, 'renovate')
    uses: ./.github/workflows/build-iso.yml
    permissions:
      actions: read
      contents: read
      packages: read
    needs: [build-image-beta]
    with:
      image_flavor: Beta

  gen-sbom-beta:
    name: Generate SBOMs (Beta)
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'beta' || inputs.flavor == 'both') &&
      (inputs.build_type == 'image' || inputs.build_type == 'both') &&
      !contains(github.head_ref, 'renovate')
    needs: [build-image-beta]
    uses: ./.github/workflows/gen-sbom.yml
    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
    with:
      image_flavor: Beta

  create-release:
    name: Create Release
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'stable' || inputs.flavor == 'both') &&
      (inputs.build_type == 'iso' || inputs.build_type == 'both') &&
      !contains(github.head_ref, 'renovate')
    needs: ["build-iso", "gen-sbom"]
    uses: ./.github/workflows/create-release.yml
    permissions:
      contents: write
    with:
      type: stable

  create-release-beta:
    name: Create Release (Beta)
    if: |
      github.event_name == 'workflow_dispatch' &&
      (inputs.flavor == 'beta' || inputs.flavor == 'both') &&
      (inputs.build_type == 'iso' || inputs.build_type == 'both') &&
      !contains(github.head_ref, 'renovate')
    needs: ["build-iso-beta", "gen-sbom-beta"]
    uses: ./.github/workflows/create-release.yml
    permissions:
      contents: write
    with:
      type: beta
